---
- name: Prepare Ubuntu machines for SSH and Install Docker
  hosts: ubuntu_docker_main_machines
  become: yes  # Use sudo for all operations
  gather_facts: yes  # Ensure facts are gathered to use ansible_facts['distribution'].lower()
  vars:
    ansible_become_pass: Cpm@st3r!

  tasks:
    - name: Ensure SSH is installed
      ansible.builtin.apt:
        name: openssh-server
        state: present

    - name: Ensure SSH service is enabled and running
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: yes

    - name: Allow SSH through the firewall
      ansible.builtin.apt:
        name: ufw
        state: present
      register: ufw_installed

    - name: Enable SSH connections on the firewall
      ansible.builtin.command: ufw allow ssh
      when: ufw_installed.changed

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker Engine
      ansible.builtin.apt:
        name: docker-ce
        state: latest

    - name: Install Python3-pip (pip3)
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        state: present
