---
- name: Install Docker on Ubuntu servers
  hosts: ubuntu_docker_main_machines
  become: yes  # Use sudo for all operations
  gather_facts: yes  # Ensure facts are gathered to use ansible_facts['distribution'].lower()
  vars:
    ansible_become_pass: Cpm@st3r!

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker Engine
      ansible.builtin.apt:
        name: docker-ce
        state: latest
