---
- name: Initial setup for Check Point GAiA using clish
  hosts: check_point
  gather_facts: no
  tasks:
    
    - name: FTC on Management Server
      raw: config_system.orig --config-string "hostname=<hostname>&domainname=<domain>&timezone='America/New_York'&ftw_sic_key=<sic_key>&install_security_gw=true&gateway_daip=false&install_ppak=true&gateway_cluster_member=false&install_security_managment=false&install_mgmt_primary=false&maintenance_hash=<maint_password_hash>"
      register: FTC_result
      ignore_errors: true

    # - name: Wait until the FTW completes
    #   stat:
    #     path: "/etc/.wizard_accepted"
    #   register: file_data
    #   until: file_data.stat.exists
    #   retries: 20
    #   delay: 30
      

    # - name: Waiting for 10 seconds before reboot
    #   pause:
    #     seconds: 10

    # - name: Rebooting
    #   raw: "shutdown -r now"

    
    