name: Spectral Linting  # Give the workflow a name

on:
  push:
    branches: 
      - raffi-cgwaf
  pull_request:
    branches: 
      - raffi-cgwaf  

jobs:
  spectral-scan:  # Name the job
    runs-on: ubuntu-latest  # Specify the OS runner

    steps:
      - uses: actions/checkout@v3  # Check out the code

      - name: Install Spectral (if needed)
        run: npm install -g @stoplight/spectral-cli  # Install Spectral

      - name: Execute Spectral Scan
        run: spectral lint **/*.yaml  # Scan all relevant files
